# Generated by Django 5.0.4 on 2024-06-10 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtDebitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=255)),
                ('cod_orgao', models.CharField(max_length=255)),
                ('orgao', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=255)),
                ('upag', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margem', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margem_cartao', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prazo', models.IntegerField()),
                ('situacao', models.CharField(max_length=255)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.baseclientes')),
            ],
            options={
                'unique_together': {('id_cliente', 'valor', 'margem', 'prazo', 'situacao')},
            },
        ),
    ]
