# Generated by Django 5.0.4 on 2024-06-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extdebitos',
            name='margem',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='extdebitos',
            name='margem_cartao',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='extdebitos',
            name='valor',
            field=models.FloatField(),
        ),
    ]
