# Generated by Django 5.0.4 on 2024-05-21 15:01

import apps.financeiro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_associado', models.CharField(max_length=100)),
                ('valor', models.CharField(blank=True, max_length=1000000, null=True)),
                ('vencimento_dia', models.IntegerField(blank=True, null=True)),
                ('Money_POA', models.BooleanField(default=False)),
                ('Money_SLE', models.BooleanField(default=False)),
                ('Money_SM', models.BooleanField(default=False)),
                ('Park_Guaiba', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pago', 'Pago'), ('A pagar', 'A pagar')], default='A pagar', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('year_month', models.CharField(blank=True, editable=False, max_length=7)),
                ('comprovante', models.FileField(upload_to=apps.financeiro.models.Comprovante.upload_to_custom)),
                ('id_gasto', models.CharField(blank=True, max_length=9999999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('vencimento_dia', models.IntegerField()),
                ('tipo_conta', models.CharField(choices=[('GERAL', 'Geral'), ('SISTEMA', 'Sistema'), ('VOIP', 'Voip')], max_length=20)),
                ('Loja', models.BooleanField(default=False)),
                ('SIAPE', models.BooleanField(default=False)),
                ('INSS', models.BooleanField(default=False)),
                ('TI', models.BooleanField(default=False)),
                ('Marketing', models.BooleanField(default=False)),
                ('Operacional', models.BooleanField(default=False)),
                ('Outros', models.BooleanField(default=False)),
                ('Money_POA', models.BooleanField(default=False)),
                ('Money_SLE', models.BooleanField(default=False)),
                ('Money_SM', models.BooleanField(default=False)),
                ('Park_Guaiba', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_associado', models.CharField(max_length=100)),
                ('valor', models.CharField(blank=True, max_length=1000000, null=True)),
                ('vencimento_dia', models.IntegerField(blank=True, null=True)),
                ('Money_POA', models.BooleanField(default=False)),
                ('Money_SLE', models.BooleanField(default=False)),
                ('Money_SM', models.BooleanField(default=False)),
                ('Park_Guaiba', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pago', 'Pago'), ('A pagar', 'A pagar')], default='A pagar', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('year_month', models.CharField(blank=True, editable=False, max_length=7)),
                ('boleto', models.FileField(upload_to=apps.financeiro.models.Gasto.upload_to_custom)),
            ],
        ),
    ]
